name: Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init
      run: |
        echo -e "machine github.com\nlogin zmaplex\npassword ${{secrets.MY_GITHUB_TOKEN}}" > ~/.netrc
        sudo mkdir -p /etc/sing-box-pro
        curl ${{secrets.SING_BOX_PRO_CONFIG_URL}} > ./server.json
        sudo mv ./server.json /etc/sing-box-pro/server.json


    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }} 
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.11
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        CGO_ENABLED=0 go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${GITHUB_REF#refs/tags/}' -s -w -buildid=" -tags with_dhcp,with_quic,with_ech ./cmd/sing-box

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Check Netflix response
      run: |
        chmod a+x sing-box
        sudo ./sing-box run -c /etc/sing-box-pro/server.json &
        response=$(curl -o /dev/null -s -w "%{http_code}\n" https://www.netflix.com/sg-zh/title/70143836)
        if [ "$response" -ne 200 ]; then
            echo "Error: HTTP response is not 200"
            exit 1
        fi
    - name: Check Openai HTTP
      run: |
            response=$(curl -o /dev/null -s -w "%{http_code}\n" https://android.chat.openai.com)
            if [ "$response" -ne 403 ]; then
                echo "Error: HTTP response is not 403"
                exit 1
            fi

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 cp sing-box s3://${{ secrets.S3_SING_BOX_BUCKET }} --acl public-read --endpoint-url https://s3-accelerate.amazonaws.com